name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: uwu

    defaults:
      run:
        working-directory: ${{ env.working-directory }}

    steps:
      - run: pwd
      
