name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: uwu

    defaults:
      run:
        working-directory: ${{ env.working-directory }}

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all -- --setup
          
  linter:
    name: clippy-check
    runs-on: ubuntu-latest
    
    env:
      working-directory: uwu

    defaults:
      run:
        working-directory: ${{ env.working-directory }}

    
    steps:
      - uses: actions/checkout@v3
      - name: Install clippy
        run: rustup component add clippy
      - name: Run linter (clippy)
        # Will fail when encountering warnings
        run: cargo clippy -- -D warnings

